<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Authors>Rirurin</Authors>
		<PackageProjectUrl>https://github.com/rirurin/UE.Toolkit.P3RClasses</PackageProjectUrl>
		<Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\UE.Toolkit\UE.Toolkit.Core\UE.Toolkit.Core.csproj" />
    </ItemGroup>

</Project>
